### ISSUE TITLE
HomepageForDomain doesn't work with www

### ISSUE THREAD

**Issue by chillu** [twohill/silverstripe-homepagefordomain#1]
Moved from http://open.silverstripe.org/ticket/4489

On a fresh install of SS 2.3.3, entering a value for "Use this page as the 'home page' for the following domains:" in behaviour tab only makes this page as homepage, when the domain is entered without www.

So entering "domain.com" works, but not "www.domain.com".

If this behaviour is wanted, please add a note in the UI.

php: PHP 5.2.0-8+etch15 mysql: 5.0.32-Debian_7etch10-log

**Comment by altwohill** [comment]
Cleaning up old issues. Please feel free to reopen if you feel the issue is still valid!
