### ISSUE TITLE
The 1st run of dev/build after installation always fails

### ISSUE THREAD

**Issue by normann** [twohill/silverstripe-homepagefordomain#21]
Replicated version: v1.0.0
Replicated environment: dev

After installation of the module, I try to run a dev/build task from CLI, it throws an error:
> Undefined index 'HTTP_HOST' at line 19 in class Twohill\HomepageForDomain\RootURLControllerExtension

Then I try to run the dev/build from a browser, it throws another error:
> Unknown column SiteTree.HomepageForDomain in WHERE clause at line 21 in class
Twohill\HomepageForDomain\RootURLControllerExtension

Produce Steps:
- Step 1: Install the module (success)
- Step 2: run 'sake dev/build' in command line (fail)
- Step 3: run /dev/build from a browser (fail)

Analysis: 
Failure at Step 2 is obvious, we need to ensure that we could get a $host from $_SERVER['HTTP_HOST'] for update a homepage link we need to check if such a $_SERVER['HTTP_HOST'] exists.
Failure at Step 3 is due to the function is executed before the column `HomepageForDomain` is created in table `SiteTree`

**Comment by normann** [comment]
#22 is the PR for this issue

**Comment by altwohill** [comment]
Welp, I should check on these more often. Better late than never I guess? Thanks for the PR!
