### ISSUE TITLE
On dev/build/?flush=1 i get the following error SS3.02

### ISSUE THREAD

**Issue by bobbush** [twohill/silverstripe-homepagefordomain#3]
Strict Standards: Declaration of HomepageForDomainExtension::extraStatics() should be compatible with that of DataExtension::extraStatics() in E:\xampp\htdocs\gr-locks\homepagefordomain\code\HomepageForDomainExtension.php on line 66

Strict Standards: Declaration of HomepageForDomainExtension::updateFieldLabels() should be compatible with that of DataExtension::updateFieldLabels() in E:\xampp\htdocs\gr-locks\homepagefordomain\code\HomepageForDomainExtension.php on line 66

**Comment by altwohill** [comment]
Cleaning up old issues. Please feel free to reopen if you feel the issue is still valid!
